ARG UBUNTU=22.04
ARG TYPE=base
FROM wpilib/ubuntu-${TYPE}:${UBUNTU}


# Install toolchain
RUN curl -SL https://github.com/wpilibsuite/opensdk/releases/download/v2025-2/armhf-raspi-bookworm-2025-x86_64-linux-gnu-Toolchain-12.2.0.tgz | sh -c 'mkdir -p /usr/local && cd /usr/local && tar xzf - --strip-components=2'

RUN echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list

RUN apt update && apt install -y temurin-21-jdk && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME /usr/lib/jvm/temurin-21-jdk-arm64

WORKDIR /
